/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dao.ClienteDAO;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Arrays;
import javax.swing.JOptionPane;
import models.Cliente;

/**
 *
 * @author 182220008
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
        defineIcone();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbNome = new javax.swing.JLabel();
        LbTelefone = new javax.swing.JLabel();
        LbCadCliente = new javax.swing.JLabel();
        LbEndereco = new javax.swing.JLabel();
        LbCpf = new javax.swing.JLabel();
        LbEmail = new javax.swing.JLabel();
        LbCidade = new javax.swing.JLabel();
        TfNome = new javax.swing.JTextField();
        TfTelefone = new javax.swing.JTextField();
        TfEndereco = new javax.swing.JTextField();
        TfCpf = new javax.swing.JTextField();
        TfEmail = new javax.swing.JTextField();
        TfCidade = new javax.swing.JTextField();
        BtCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de cliente");

        LbNome.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        LbNome.setText("Nome");

        LbTelefone.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        LbTelefone.setText("Telefone");

        LbCadCliente.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        LbCadCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbCadCliente.setText("Cadastro de cliente");

        LbEndereco.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        LbEndereco.setText("Endereco");

        LbCpf.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        LbCpf.setText("CPF");

        LbEmail.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        LbEmail.setText("E-mail");

        LbCidade.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        LbCidade.setText("Cidade");

        TfNome.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        TfTelefone.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        TfEndereco.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        TfCpf.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        TfEmail.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        TfCidade.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        BtCadastrar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        BtCadastrar.setText("Cadastrar");
        BtCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LbCadCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbEndereco)
                            .addComponent(LbNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(TfTelefone)
                            .addComponent(TfEndereco))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LbCidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LbCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(TfCpf)
                            .addComponent(TfCidade))))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(BtCadastrar)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(LbCadCliente)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNome)
                    .addComponent(LbCpf)
                    .addComponent(TfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbTelefone)
                    .addComponent(LbEmail)
                    .addComponent(TfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbEndereco)
                    .addComponent(LbCidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(BtCadastrar)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadastrarActionPerformed
        try{
        Cliente cli = criaCliente();
        ClienteDAO.cadastra(cli);
        JOptionPane.showMessageDialog(this, "Cliente cadastrado com sucesso", getTitle(), JOptionPane.INFORMATION_MESSAGE);
        
        dispose();
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, String.format("Erro ao cadastrar cliente:\n%s", e.getMessage()), getTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtCadastrarActionPerformed

    private void defineIcone(){
        Image icone16= Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Img/16.png"));
        Image icone32= Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Img/32.png"));
        Image icone64= Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Img/64.png"));
        Image icone128= Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Img/128.png"));
        setIconImages(Arrays.asList(icone16,icone32, icone64, icone128));
    }
   
    public Cliente criaCliente(){
        
        
        String nome =(TfNome.getText());
        String cpf = (TfCpf.getText());
        String telefone =(TfTelefone.getText());
        String email = (TfEmail.getText());
        String endereco = (TfEndereco.getText());
        String cidade =(TfCidade.getText());
        
        
        return new Cliente(nome, cpf, telefone, email, endereco, cidade);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCadastrar;
    private javax.swing.JLabel LbCadCliente;
    private javax.swing.JLabel LbCidade;
    private javax.swing.JLabel LbCpf;
    private javax.swing.JLabel LbEmail;
    private javax.swing.JLabel LbEndereco;
    private javax.swing.JLabel LbNome;
    private javax.swing.JLabel LbTelefone;
    private javax.swing.JTextField TfCidade;
    private javax.swing.JTextField TfCpf;
    private javax.swing.JTextField TfEmail;
    private javax.swing.JTextField TfEndereco;
    private javax.swing.JTextField TfNome;
    private javax.swing.JTextField TfTelefone;
    // End of variables declaration//GEN-END:variables
}
