/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dao.ClienteDAO;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Arrays;
import javax.swing.JOptionPane;
import models.Cliente;

/**
 *
 * @author 182220008
 */
public class FormularioCliente extends javax.swing.JFrame {

    private Cliente cliente;

    public FormularioCliente() {
        initComponents();
        defineIcone();
    }

    public FormularioCliente(Cliente cliente) {
        this.cliente = cliente;
        initComponents();
        defineIcone();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbNome = new javax.swing.JLabel();
        LbTelefone = new javax.swing.JLabel();
        LbCadCliente = new javax.swing.JLabel();
        LbEndereco = new javax.swing.JLabel();
        LbCpf = new javax.swing.JLabel();
        LbEmail = new javax.swing.JLabel();
        LbCidade = new javax.swing.JLabel();
        TfNome = new javax.swing.JTextField();
        TfTelefone = new javax.swing.JTextField();
        TfEndereco = new javax.swing.JTextField();
        TfCpf = new javax.swing.JTextField();
        TfEmail = new javax.swing.JTextField();
        TfCidade = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(cliente != null ? "Edição de cliente" : "Cadastro de cliente");

        LbNome.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        LbNome.setText("Nome");

        LbTelefone.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        LbTelefone.setText("Telefone");

        LbCadCliente.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        LbCadCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbCadCliente.setText(cliente != null ? "Edição de cliente" : "Cadastro de cliente");

        LbEndereco.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        LbEndereco.setText("Endereco");

        LbCpf.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        LbCpf.setText("CPF");

        LbEmail.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        LbEmail.setText("E-mail");

        LbCidade.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        LbCidade.setText("Cidade");

        TfNome.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        TfNome.setText(cliente != null ? cliente.getNome() : "");
        TfNome.setPreferredSize(null);

        TfTelefone.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        TfTelefone.setText(cliente != null ? cliente.getTelefone(): "");
        TfTelefone.setPreferredSize(null);

        TfEndereco.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        TfEndereco.setText(cliente != null ? cliente.getEndereco(): "");
        TfEndereco.setPreferredSize(null);

        TfCpf.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        TfCpf.setText(cliente != null ? cliente.getCpf(): "");
        TfCpf.setPreferredSize(null);

        TfEmail.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        TfEmail.setText(cliente != null ? cliente.getEmail(): "");
        TfEmail.setPreferredSize(null);

        TfCidade.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        TfCidade.setText(cliente != null ? cliente.getCidade(): "");
        TfCidade.setPreferredSize(null);

        btSalvar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LbCadCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbEndereco)
                            .addComponent(LbNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LbCidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LbCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(btSalvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(LbCadCliente)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNome)
                    .addComponent(LbCpf)
                    .addComponent(TfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbTelefone)
                    .addComponent(LbEmail)
                    .addComponent(TfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbEndereco)
                    .addComponent(LbCidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btSalvar)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        try {
            Cliente cli = criaCliente();
            if (this.cliente != null) {
                cli.setId(cliente.getId());
                ClienteDAO.editaCliente(cli);
                JOptionPane.showMessageDialog(this, "Cliente atualizado com sucesso", getTitle(), JOptionPane.INFORMATION_MESSAGE);
            } else {
                ClienteDAO.cadastra(cli);
                JOptionPane.showMessageDialog(this, "Cliente cadastrado com sucesso", getTitle(), JOptionPane.INFORMATION_MESSAGE);
            }
            

            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, String.format("Erro ao cadastrar cliente:\n%s", e.getMessage()), getTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void defineIcone() {
        Image icone16 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Img/16.png"));
        Image icone32 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Img/32.png"));
        Image icone64 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Img/64.png"));
        Image icone128 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Img/128.png"));
        setIconImages(Arrays.asList(icone16, icone32, icone64, icone128));
    }

    public Cliente criaCliente() {

        String nome = (TfNome.getText());
        String cpf = (TfCpf.getText());
        String telefone = (TfTelefone.getText());
        String email = (TfEmail.getText());
        String endereco = (TfEndereco.getText());
        String cidade = (TfCidade.getText());

        return new Cliente(nome, cpf, telefone, email, endereco, cidade);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbCadCliente;
    private javax.swing.JLabel LbCidade;
    private javax.swing.JLabel LbCpf;
    private javax.swing.JLabel LbEmail;
    private javax.swing.JLabel LbEndereco;
    private javax.swing.JLabel LbNome;
    private javax.swing.JLabel LbTelefone;
    private javax.swing.JTextField TfCidade;
    private javax.swing.JTextField TfCpf;
    private javax.swing.JTextField TfEmail;
    private javax.swing.JTextField TfEndereco;
    private javax.swing.JTextField TfNome;
    private javax.swing.JTextField TfTelefone;
    private javax.swing.JButton btSalvar;
    // End of variables declaration//GEN-END:variables
}
