/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dao.AutomovelDAO;
import dao.CemiterioCapelaDAO;
import dao.ClienteDAO;
import dao.DefuntoDAO;
import dao.FornecedorFloresDAO;
import dao.ServicoDAO;
import dao.UrnaFunerariaDAO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import models.Automovel;
import models.CemiterioCapela;
import models.Cliente;
import models.Defunto;
import models.FornecedorFlores;
import models.Servico;
import models.UrnaFuneraria;


/**
 *
 * @author 182220008
 */
public class VendaServico extends javax.swing.JFrame {

    /**
     * Creates new form VendaServico
     */
    public VendaServico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCliente1 = new javax.swing.JLabel();
        LbServico = new javax.swing.JLabel();
        CbCliente = new javax.swing.JComboBox<>();
        CemiterioCapela[] listaCc = CemiterioCapelaDAO.buscaTodos().toArray(CemiterioCapela[]::new);
        DefaultComboBoxModel<CemiterioCapela> comboCcModel = new DefaultComboBoxModel<>(listaCc);
        CbxCapela = new javax.swing.JComboBox<>();
        CbxServico = new javax.swing.JComboBox<>();
        Defunto[] listaDefuntos = DefuntoDAO.buscaTodos().toArray(Defunto[]::new);
        DefaultComboBoxModel<Defunto> comboDefuntoModel = new DefaultComboBoxModel<>(listaDefuntos);
        CbDefunto = new javax.swing.JComboBox<>();
        FornecedorFlores[] listaFf = FornecedorFloresDAO.buscaTodos().toArray(FornecedorFlores[]::new);
        DefaultComboBoxModel<FornecedorFlores> comboFfModel = new DefaultComboBoxModel<>(listaFf);
        CbxFornFlores = new javax.swing.JComboBox<>();
        Automovel[] listaAut = AutomovelDAO.buscaTodos().toArray(Automovel[]::new);
        DefaultComboBoxModel<Automovel> comboAutModel = new DefaultComboBoxModel<>(listaAut);
        CbxAutomovel = new javax.swing.JComboBox<>();
        LbPreco = new javax.swing.JLabel();
        LbCifrao = new javax.swing.JLabel();
        BtCadServico = new javax.swing.JButton();
        LbValor = new javax.swing.JLabel();
        UrnaFuneraria[] listaUf = UrnaFunerariaDAO.buscaTodos().toArray(UrnaFuneraria[]::new);
        DefaultComboBoxModel<UrnaFuneraria> comboUfModel = new DefaultComboBoxModel<>(listaUf);
        CbxUrnaFuneraria = new javax.swing.JComboBox<>();
        lbCliente = new javax.swing.JLabel();
        lbDefunto = new javax.swing.JLabel();
        lbCemiterioCapela = new javax.swing.JLabel();
        lbFornecedorFlores = new javax.swing.JLabel();
        lbServico1 = new javax.swing.JLabel();
        lbAutomovel = new javax.swing.JLabel();
        lbUrnaFuneraria = new javax.swing.JLabel();

        lbCliente1.setText("Cliente");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LbServico.setText("Serviço/Venda");

        Cliente[] listaClientes = ClienteDAO.buscaTodos().toArray(Cliente[]::new);
        DefaultComboBoxModel<Cliente> comboClienteModel = new DefaultComboBoxModel<>(listaClientes);
        CbCliente.setMaximumRowCount(10);
        CbCliente.setModel(comboClienteModel);

        CbxCapela.setModel(comboCcModel);

        CbxServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funeral", "Cremação" }));

        CbDefunto.setModel(comboDefuntoModel);

        CbxFornFlores.setModel(comboFfModel);

        CbxAutomovel.setModel(comboAutModel);

        LbPreco.setText("Preço");

        LbCifrao.setText("R$");

        BtCadServico.setText("Cadastro do serviço");
        BtCadServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadServicoActionPerformed(evt);
            }
        });

        CbxUrnaFuneraria.setModel(comboUfModel);

        lbCliente.setText("Cliente");

        lbDefunto.setText("Defunto");

        lbCemiterioCapela.setText("Cemitério/Capela");

        lbFornecedorFlores.setText("Fornecedor de flores");

        lbServico1.setText("Serviço");

        lbAutomovel.setText("Automóvel");

        lbUrnaFuneraria.setText("Urna Funerária");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtCadServico)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbServico)
                        .addGap(34, 34, 34)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbUrnaFuneraria, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCemiterioCapela, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CbxUrnaFuneraria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CbCliente, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CbxServico, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CbxCapela, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbServico1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(LbPreco)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LbCifrao)
                                    .addGap(18, 18, 18)
                                    .addComponent(LbValor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbDefunto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CbxAutomovel, 0, 106, Short.MAX_VALUE)
                                        .addComponent(CbDefunto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CbxFornFlores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lbAutomovel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lbFornecedorFlores, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(LbServico)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lbCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbDefunto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbDefunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFornecedorFlores)
                    .addComponent(lbServico1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbxFornFlores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbxServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCemiterioCapela)
                    .addComponent(lbAutomovel))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbxCapela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbxAutomovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(lbUrnaFuneraria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LbValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LbPreco)
                        .addComponent(LbCifrao)
                        .addComponent(CbxUrnaFuneraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtCadServico)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtCadServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadServicoActionPerformed
try{
        Servico serv = criaServico();
        ServicoDAO.cadastra(serv);
        JOptionPane.showMessageDialog(this, "Serviço cadastrado com sucesso", getTitle(), JOptionPane.INFORMATION_MESSAGE);
        dispose();
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, String.format("Erro ao cadastrar cliente:\n%s", e.getMessage()), getTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtCadServicoActionPerformed

   
    
    public Servico criaServico(){
        Cliente cli = CbCliente.getItemAt(CbCliente.getSelectedIndex());
        Defunto def = CbDefunto.getItemAt(CbDefunto.getSelectedIndex());
        String tipoServico = CbxServico.getItemAt(CbxServico.getSelectedIndex());
        FornecedorFlores ff = CbxFornFlores.getItemAt(CbxFornFlores.getSelectedIndex());
        CemiterioCapela cc = CbxCapela.getItemAt(CbxCapela.getSelectedIndex());
        Automovel aut = CbxAutomovel.getItemAt(CbxAutomovel.getSelectedIndex());
        UrnaFuneraria uf = CbxUrnaFuneraria.getItemAt(CbxUrnaFuneraria.getSelectedIndex());
        
        float valor = uf.getValor();
        
        Servico serv = new Servico(tipoServico, valor, aut, ff, cc, uf, cli, def);
        
        return serv;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCadServico;
    private javax.swing.JComboBox<Cliente> CbCliente;
    private javax.swing.JComboBox<Defunto> CbDefunto;
    private javax.swing.JComboBox<Automovel> CbxAutomovel;
    private javax.swing.JComboBox<CemiterioCapela> CbxCapela;
    private javax.swing.JComboBox<FornecedorFlores> CbxFornFlores;
    private javax.swing.JComboBox<String> CbxServico;
    private javax.swing.JComboBox<UrnaFuneraria> CbxUrnaFuneraria;
    private javax.swing.JLabel LbCifrao;
    private javax.swing.JLabel LbPreco;
    private javax.swing.JLabel LbServico;
    private javax.swing.JLabel LbValor;
    private javax.swing.JLabel lbAutomovel;
    private javax.swing.JLabel lbCemiterioCapela;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbCliente1;
    private javax.swing.JLabel lbDefunto;
    private javax.swing.JLabel lbFornecedorFlores;
    private javax.swing.JLabel lbServico1;
    private javax.swing.JLabel lbUrnaFuneraria;
    // End of variables declaration//GEN-END:variables
}
